### ISSUE TITLE
keywords inside comments are wrongly recognized

### ISSUE THREAD

**Issue by Krox** [amehat/atom-language-d#13]
some keywords (at least const, immutable, shared, body, in, out. maybe more) are highlighted even when inside comments. Most of the time this just means comments are more colorful than they should. A more severe example is the following code where all highlighting is turned off after the function foo for the remainder of the file.

```
void foo() // out
{
    int x = 5;
}

void bar()
{
    int x = 7;
}
```

**Comment by jzhu98** [comment]
Fixed in the latest version (3.3.0).
