### ISSUE TITLE
Grammar issue for bool

### ISSUE THREAD

**Issue by dchammond** [amehat/atom-language-d#3]
I noticed that bool was not being highlighted, all though most other types were highlighted (void, int, etc...).  The fix I found for this was in grammars/d.cson, every time the data types were declared, "boolean" was used instead of "bool".  This happens 4 times.  Switching the word "boolean" to "bool" allowed "bool" to be highlighted in the same manner as other data types. Below are the "fixed" versions with "boolean" changed to "bool".
The first two instances were on lines 733 and 740 (with no wrapping on the code lines) 

![bool 1-2](https://cloud.githubusercontent.com/assets/5134986/3473476/38405954-02d8-11e4-8fa2-9cc29f4fc5cb.png)

and the second two instances were on line 814.

![bool 3](https://cloud.githubusercontent.com/assets/5134986/3473477/38419ae4-02d8-11e4-926f-0b88a45d15ac.png)
![bool 4](https://cloud.githubusercontent.com/assets/5134986/3473478/3841ef44-02d8-11e4-9280-6d05d56927af.png)

**Comment by jzhu98** [comment]
Fixed in pull request #4.
