### ISSUE TITLE
Causes Atom to hang on OS X

### ISSUE THREAD

**Issue by luke5542** [amehat/atom-language-d#5]
Under OS X 10.10.1, and Atom version 0.175.0, typing something like:

```D
void someMethod(){}
```

causes Atom to hang and become unresponsive before displaying the `{}`

**Comment by luke5542** [comment]
Okay, I found out that by removing the code:

```
{
    'begin': '(?<=\\))'
    'end': '(?=\\{|in|out|body)'
    'name': 'meta.function.attributes.d'
    'patterns': [
      {
        'include': '#attributes'
      }
    ]
}
```

from grammars/d.cson I no longer get the error. I don't know enough about this system to make a significant fix, but for now I'm removing it from mine.

**Comment by jzhu98** [comment]
Typed it in, and presto! Instant powerpoint!
By the way, kudos on finding the specific pattern that caused the crash.
I believe it's due to the end lookbehind that tries to match the same position as the begin pattern, and fails. I'll push a fix within the next few days.
