### ISSUE TITLE
Some font ligatures don't work with this package

### ISSUE THREAD

**Issue by nikibobi** [amehat/atom-language-d#9]
I installed Monoid font that has ligatures in it. I have no problem with the other languages displaying the ligatures. But when I try in D some of them work, but others don't.

Working:
* <=
* //

Not working
* ==
* !=
* >=

I'm not sure where the issue is and would be happy if someone can find the problem.

**Comment by jzhu98** [comment]
Could you point me to a few other languages that display ligatures correctly?

My first guess is that this code snippet doesn't assign the right scope (the name field below) to them. Maybe they require a special scope for equality and inequality?

```cson
grammars/d.cson (line 453)
---
{
  'match': '(==|!=|<=|>=|<>|<|>)'
  'name': 'keyword.operator.comparison.d'
}
```

I don't expect to have time to work on it until January, owing to college apps, but I'll see what I can sneak in.

**Comment by nikibobi** [comment]
C/C++ and plain text and many others display them correctly. The strange part is that `<=` works, but `!=` and `>=` don't.
